### ISSUE TITLE
Mute Skip Suggestion. 

### ISSUE THREAD

**Issue by kaotester** [Russell0014/Binge-Ad-Auto-Skip#1]
Thanks for making this. Works well so far. 
I installed this using the chrome webstore.
When the skip happens the sped up audio was audible to me. I think it would be better if it was muted.  Doesn't really cause issues so it's just a suggestion.

**Comment by Russell0014** [comment]
I've added the mute feature and have just published the update on the Chrome Web Store. It should be available within a day or two.
